databaseChangeLog:

  - changeSet:
      id: 004-initial-superuser-role
      author: core
      context: data
      runOnChange: false
      runAlways: false

      preConditions:
        onFail: MARK_RAN
        onError: HALT

        not:
          sqlCheck:
            expectedResult: 1
            sql: >
              SELECT COUNT(1)
              FROM rol
              WHERE nombre = 'superuser'

      changes:
        - insert:
            tableName: rol
            columns:
              - column:
                  name: nombre
                  value: superuser

              - column:
                  name: descripcion
                  value: Rol con acceso total al sistema

              - column:
                  name: is_deleted
                  valueBoolean: false
