databaseChangeLog:

  - changeSet:
      id: 005-initial-superuser-user
      author: core
      context: data

      preConditions:
        onFail: MARK_RAN
        onError: HALT

        not:
          sqlCheck:
            expectedResult: 1
            sql: >
              SELECT COUNT(1)
              FROM "user"
              WHERE username = 'superuser'

      changes:
        - insert:
            tableName: "user"
            columns:
              - column:
                  name: username
                  value: superuser

              - column:
                  name: password
                  value: "__DJANGO_HASH_AQUI__"

              - column:
                  name: is_active
                  valueBoolean: true

              - column:
                  name: is_staff
                  valueBoolean: true

              - column:
                  name: is_superuser
                  valueBoolean: true

              - column:
                  name: activo
                  valueBoolean: true

              - column:
                  name: is_deleted
                  valueBoolean: false
