services:
  postgres:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 142857
      POSTGRES_DB: postgres
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  liquibase:
    image: liquibase/liquibase:5.0
    container_name: monorepo-liquibase
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./liquibase:/workspace
      - ./liquibase/drivers:/liquibase/lib
    working_dir: /workspace
    command: >
      --defaultsFile=/workspace/liquibase.properties update

volumes:
  pgdata:
