databaseChangeLog:
  - changeSet:
      id: base-004-initial-user
      author: esteban
      context: bootstrap

      changes:
        - insert:
            tableName: auth_user
            columns:
              - column:
                  name: username
                  value: esteban

              - column:
                  name: password
                  value: pbkdf2_sha256$1200000$IXkJMXbleuwJTozKLZMFuK$+NsOKcrCU6LcXm4f1TZL2ruIIxmsm2UNDvs+XRyvECA=$600000$changeme$changemehash

              - column:
                  name: first_name
                  value: Esteban

              - column:
                  name: last_name
                  value: Serafini

              - column:
                  name: email
                  value: esteban@example.com

              - column:
                  name: is_superuser
                  valueBoolean: true

              - column:
                  name: is_staff
                  valueBoolean: true

              - column:
                  name: is_active
                  valueBoolean: true

              - column:
                  name: date_joined
                  valueDate: NOW()

              # BaseModel
              - column:
                  name: is_deleted
                  valueBoolean: false

              - column:
                  name: createdat
                  valueDate: NOW()

              - column:
                  name: updatedat
                  valueDate: NOW()

              # TEMPORALMENTE NULL
              - column:
                  name: createdby_id
                  valueNumeric: null

              - column:
                  name: updatedby_id
                  valueNumeric: null
