databaseChangeLog:
  - changeSet:
      id: 001-create-role
      author: sistema
      changes:
        - createTable:
            tableName: role
            columns:
              - column:
                  name: id
                  type: SERIAL
                  constraints:
                    primaryKey: true
              - column:
                  name: nombre
                  type: VARCHAR(50)
                  constraints:
                    nullable: false
                    unique: true
              - column:
                  name: descripcion
                  type: TEXT
