databaseChangeLog:
  - changeSet:
      id: 002-create-user-role
      author: sistema
      changes:
        - createTable:
            tableName: user_role
            columns:
              - column:
                  name: id
                  type: SERIAL
                  constraints:
                    primaryKey: true
              - column:
                  name: user_id
                  type: INT
                  constraints:
                    nullable: false
              - column:
                  name: role_id
                  type: INT
                  constraints:
                    nullable: false

        - addUniqueConstraint:
            tableName: user_role
            columnNames: user_id, role_id

        - addForeignKeyConstraint:
            baseTableName: user_role
            baseColumnNames: user_id
            referencedTableName: base_user
            referencedColumnNames: id
            onDelete: CASCADE

        - addForeignKeyConstraint:
            baseTableName: user_role
            baseColumnNames: role_id
            referencedTableName: role
            referencedColumnNames: id
            onDelete: CASCADE
